# Generated by Django 4.2.5 on 2023-11-28 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_app', '0002_reservas_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='cantidad_personas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='correo',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
