# Generated by Django 4.2.5 on 2023-11-28 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_app', '0003_alter_reservas_cantidad_personas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(max_length=80, validators=[django.core.validators.MaxLengthValidator(80)]),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='telefono',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
