# Generated by Django 4.2.5 on 2023-11-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_app', '0005_alter_reservas_correo_alter_reservas_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
