# Generated by Django 4.2.5 on 2023-11-28 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion_app', '0006_alter_reservas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(max_length=80, validators=[django.core.validators.MaxLengthValidator(80)]),
        ),
    ]
